font: JetBrainsMono Nerd Font 16
background: "#1a1b26"
color: "#c0caf5"
border: "#7fc8ff"
separator: "    "
border_width: 1
corner_r: 0
padding: 20
anchor: center
menu:
  - key: "k"
    desc: keybr.com
    cmd: webapp keybr https://www.keybr.com/
  - key: "w"
    desc: WhatsApp
    cmd: webapp whatsapp https://web.whatsapp.com/
  - key: "v"
    desc: Volume
    submenu:
      - key: ","
        desc: Lower
        cmd: swayosd-client --output-volume lower
        keep_open: true
      - key: "."
        desc: Raise
        cmd: swayosd-client --output-volume raise
        keep_open: true
      - key: "/"
        desc: Mute/unmute
        cmd: swayosd-client --output-volume mute-toggle
        keep_open: true
  - key: "b"
    desc: Brightness
    submenu:
      - key: ","
        desc: Lower
        cmd: swayosd-client --brightness lower
        keep_open: true
      - key: "."
        desc: Raise
        cmd: swayosd-client --brightness raise
        keep_open: true
      - key: "<" # This is not displayed in the menu for some reason
        desc: Set minimum
        cmd: swayosd-client --brightness 0
        keep_open: true
      - key: ">"
        desc: Set maximum
        cmd: swayosd-client --brightness 100
        keep_open: true
  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Suspend
        cmd: systemctl suspend
      - key: "r"
        desc: Soft reboot
        cmd: systemctl soft-reboot
      - key: "R"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Power-off
        cmd: systemctl poweroff
