#-------------------------------------------------------------------------------
# UI

"ui.text" = "fg"
"ui.background" = { bg = "bg", fg = "fg" }
"ui.selection" = { bg = "#333333" }

# DIAGNOSTICS

error = "red"
warning = "yellow"
info = "green"
hint = "green"

"diagnostic.error" = "red"
"diagnostic.warning" = "yellow"
"diagnostic.info" = "green"
"diagnostic.hint" = "green"

#-------------------------------------------------------------------------------
# CODE

keyword = "purple"
label = "purple"
"type.builtin" = "purple"
"variable.builtin" = "purple"
"function.builtin" = "purple"
"constant.builtin" = "purple"

type = "magenta"

comment = "gray"

"constant.numeric" = "cyan"
"type.parameter" = "cyan"

string = "green"
"string.special.symbol" = "green"
"constant.character" = "green"

constant = "fg"
punctuation = "fg"
operator = "fg"
attribute = "fg"
variable = "fg"
namespace = "fg"
function = "fg"
tag = "fg"
constructor = "fg"
special = "fg"
"function.macro" = "fg"

# MARKUP

"markup.heading" = { fg = "white", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

#-------------------------------------------------------------------------------
[palette]

bg = "#1a1a1a"
fg = "#b6b6b6"
gray = "#777777"
black = "#000000"
white = "#e0e0e0"
purple = "#de8ade"
magenta = "#bb9af7"
teal = "#7fa396"
cyan = "#9eb1ff"
green = "#98c379"
orange = "#ff9e64"
yellow = "#ffff57"
red = "#ee518a"
