#-------------------------------------------------------------------------------
# UI

"ui.text" = "fg"
"ui.background" = { bg = "bg", fg = "fg" }
"ui.selection" = { bg = "#333333" }

# DIAGNOSTICS

error = "red"
warning = "yellow"
info = "green"
hint = "green"

"diagnostic.error" = "red"
"diagnostic.warning" = "yellow"
"diagnostic.info" = "green"
"diagnostic.hint" = "green"

#-------------------------------------------------------------------------------
# CODE

keyword = "teal"
label = "teal"
"type.builtin" = "teal"
"variable.builtin" = "teal"
"function.builtin" = "teal"
"constant.builtin" = "teal"

type = "off_white"
# type = "fg"

comment = "green"
"comment.line.documentation" = "green"
"comment.block.documentation" = "green"

"constant.numeric" = "magenta"
"type.parameter" = "magenta"

string = "purple"
"string.special.symbol" = "purple"
"constant.character" = "purple"

punctuation = "gray"

constant = "fg"
operator = "fg"
attribute = "fg"
variable = "fg"
namespace = "fg"
function = "fg"
tag = "fg"
constructor = "fg"
special = "fg"
"function.macro" = "fg"

# MARKUP

"markup.heading" = { fg = "off_white", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

#-------------------------------------------------------------------------------
[palette]

bg = "#181818"
fg = "#b6b6b6"
gray = "#777777"
black = "#000000"
off_white = "#e0e0e0"
purple = "#cd9bcd"
magenta = "#bb9af7"
teal = "#7fa396"
cyan = "#9eb1ff"
green = "#98c379"
orange = "#ff9e64"
yellow = "#ffff57"
red = "#ee518a"
